/* Generated by voa — link into libasgard_logic.so (ASGARDNT payload). */
#include <jni.h>
#include <string.h>

/* AOT logic provides this symbol (same ABI as iOS). */
extern void asgard_invoke_export(const char *name);

static JavaVM *g_asgard_java_vm = NULL;

static void invoke_export_jni(JNIEnv *env, jstring jname) {
    const char *name = (*env)->GetStringUTFChars(env, jname, NULL);
    if (name) {
        asgard_invoke_export(name);
        (*env)->ReleaseStringUTFChars(env, jname, name);
    }
}

JNIEXPORT void JNICALL
Java_com_asgard_runtime_AsgardHostBridge_invokeExport(JNIEnv *env, jclass cls, jstring name) {
    (void)cls;
    invoke_export_jni(env, name);
}

static void patch_from_native_jni(JNIEnv *env, jstring jkey, jstring jvalue) {
    jclass bridge = (*env)->FindClass(env, "com/asgard/runtime/AsgardHostBridge");
    if (!bridge) return;
    jmethodID mid = (*env)->GetStaticMethodID(env, bridge, "patchFromNative", "(Ljava/lang/String;Ljava/lang/String;)V");
    if (!mid) return;
    (*env)->CallStaticVoidMethod(env, bridge, mid, jkey, jvalue);
}

/* Native → Kotlin reactive patch (called from AOT after signal updates). */
void asgard_patch_native(const char *key, const char *value) {
    JavaVM *vm = NULL;
    JNIEnv *env = NULL;
    if (g_asgard_java_vm == NULL) return;
    vm = g_asgard_java_vm;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        if ((*vm)->AttachCurrentThread(vm, &env, NULL) != 0) return;
    }
    jstring jkey = (*env)->NewStringUTF(env, key ? key : "");
    jstring jvalue = (*env)->NewStringUTF(env, value ? value : "");
    patch_from_native_jni(env, jkey, jvalue);
    (*env)->DeleteLocalRef(env, jkey);
    (*env)->DeleteLocalRef(env, jvalue);
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    (void)reserved;
    g_asgard_java_vm = vm;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) return JNI_ERR;
    jclass cls = (*env)->FindClass(env, "com/asgard/runtime/AsgardHostBridge");
    if (!cls) return JNI_ERR;
    JNINativeMethod methods[] = {
        {"invokeExport", "(Ljava/lang/String;)V",
         (void *)Java_com_asgard_runtime_AsgardHostBridge_invokeExport},
    };
    if ((*env)->RegisterNatives(env, cls, methods, 1) != 0) return JNI_ERR;
    return JNI_VERSION_1_6;
}
