# Generated by MiddlewareInjector — do not edit
namespace atlas.core;

using std.text;
using atlas.http;

micro atlas_invoke_middleware(name: utf8, middleware: AtlasMiddleware, mut ctx: AtlasRouteContext, next_index: i32, mut pipeline: MiddlewarePipeline, mut host: AtlasHost): unit {
    if name.equals("exception") {
        exception_middleware_step(middleware, ctx, next_index, pipeline, host)
        return
    }
    if name.equals("request-log") {
        request_log_middleware_step(middleware, ctx, next_index, pipeline, host)
        return
    }
    if name.equals("response-log") {
        response_log_middleware_step(middleware, ctx, next_index, pipeline, host)
        return
    }
    if name.equals("websocket") {
        websocket_middleware_step(middleware, ctx, next_index, pipeline, host)
        return
    }
    pipeline.execute_at(next_index, ctx, host)
}
