# Generated by ConfigInjector — do not edit
namespace atlas.config;

using std.text;

class AtlasListenConfig {
    host: utf8
    port: i32
}

class AtlasTlsConfig {
    enabled: bool
    cert_path: utf8
    key_path: utf8
    min_version: utf8
}

class AtlasRuntimeConfig {
    listen: AtlasListenConfig
    tls: AtlasTlsConfig
}

imply AtlasRuntimeConfig {
    micro defaults(): Self {
        return Self {
            listen: AtlasListenConfig { host: "0.0.0.0", port: 8080 },
            tls: AtlasTlsConfig { enabled: false, cert_path: "", key_path: "", min_version: "1.2" }
        }
    }

    micro validate(self): bool {
        if self.listen.port <= 0 {
            return false
        }
        if self.tls.enabled && self.tls.cert_path.is_empty() {
            return false
        }
        if self.tls.enabled && self.tls.key_path.is_empty() {
            return false
        }
        return true
    }

    micro tls_config(self): std.network.tls.TlsConfig {
        if self.tls.enabled == false {
            return std.network.tls.TlsConfig::client()
        }
        return std.network.tls.TlsConfig::server(self.tls.cert_path, self.tls.key_path)
    }
}

micro load_runtime_config(source: utf8): AtlasRuntimeConfig {
    let mut config: AtlasRuntimeConfig = AtlasRuntimeConfig::defaults()
    if source.contains("tls.enabled: true") || source.contains("tls.enabled:true") {
        config.tls.enabled = true
    }
    if source.contains("cert:") {
        config.tls.cert_path = "certs/server.pem"
    }
    if source.contains("key:") {
        config.tls.key_path = "certs/server.key"
    }
    if source.contains("port: 8443") || source.contains("port:8443") {
        config.listen.port = 8443
    }
    return config
}

micro validate_config_source(source: utf8): bool {
    let config: AtlasRuntimeConfig = load_runtime_config(source)
    return config.validate()
}
