# Generated by RouteInjector — do not edit
namespace atlas.core;

using std.text;
using atlas.http;
using atlas.wire;

micro atlas_register_routes(mut host: AtlasHost): AtlasHost {
    host = host.get_route("/api/health", "health")
    host = host.get_route("/health/live", "health_live")
    host = host.get_route("/health/ready", "health_ready")
    host = host.get_route("/api/orders", "orders")
    host = host.get_route("/api/users", "users")
    return host
}

micro atlas_invoke_handler(handler_id: utf8, ctx: AtlasRouteContext, container: AtlasWireContainer): AtlasResult {
    if handler_id.equals("health") {
        let _ctx: AtlasRouteContext = ctx
        let controller: HealthController = HealthController::wire(container)
        return controller.get_health()
    }
    if handler_id.equals("health_live") {
        let _ctx: AtlasRouteContext = ctx
        let controller: HealthController = HealthController::wire(container)
        return controller.get_live()
    }
    if handler_id.equals("health_ready") {
        let _ctx: AtlasRouteContext = ctx
        let controller: HealthController = HealthController::wire(container)
        return controller.get_ready()
    }
    if handler_id.equals("orders") {
        let _ctx: AtlasRouteContext = ctx
        let controller: OrdersController = OrdersController::wire(container)
        return controller.get_orders()
    }
    if handler_id.equals("users") {
        let _ctx: AtlasRouteContext = ctx
        let controller: UsersController = UsersController::wire(container)
        return controller.get_users()
    }
    return AtlasResult::not_found()
}
