# Generated by WsHandlerInjector — do not edit
namespace atlas.ws;

using std.text;

micro atlas_invoke_ws_handler(handler_id: utf8, event: utf8, mut ctx: AtlasWebSocketContext, message: utf8): unit {
    if handler_id.equals("echo") {
        invoke_echo_handler(event, ctx, message)
        return
    }
    if handler_id.equals("chat") {
        invoke_chat_handler(event, ctx, message)
        return
    }
}

micro atlas_register_ws_routes(mut table: AtlasWebSocketRouteTable): AtlasWebSocketRouteTable {
    table = table.map("/ws/echo", "echo")
    table = table.map("/ws/chat", "chat")
    return table
}
